# .github/workflows/deploy.yml
name: Build and Deploy Astro

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: "Trigger deployment?"
        required: false
        default: "false"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PORTFOLIO_PAT: ${{ secrets.PORTFOLIO_PAT }}
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libcairo2-dev \
            libjpeg-dev \
            libpango1.0-dev \
            libgif-dev \
            librsvg2-dev \
            libvips-dev \
            libxml2-dev \
            libxslt1-dev \
            pkg-config

      - name: Checkout site repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: npm ci

      - name: Clone photo portfolio
        run: |
          rm -rf photo-portfolio
          git clone --depth=1 https://${PORTFOLIO_PAT}:@github.com/blakesanie/photo-portfolio.git

      - name: Integrate photo portfolio
        run: |
          cp photo-portfolio/imageEmbeddings.json public/assets/imageEmbeddings.json
          python3 src/tooling/randomize_embeddings_file.py

      - name: Astro Build
        run: npm run build

      - name: Next Build
        run: |
          cd next
          npm ci
          npm run build
          cd ..
          rm -rf next/out/404
          cp -rn next/out/* dist/

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: "--prod" #Optional
