# .github/workflows/deploy.yml
name: Build and Deploy Astro

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: "Trigger deployment?"
        required: false
        default: "false"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PORTFOLIO_PAT: ${{ secrets.PORTFOLIO_PAT }}
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev libvips-dev

      - name: Checkout site repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run export
        env:
          NODE_ENV: production

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          prod: true
